---
apiVersion: v1
kind: Namespace
metadata:
  name: artifact-flow-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-flow-api
  namespace: artifact-flow-api
spec:
  selector:
    matchLabels:
      app: artifact-flow-api
      department: artifact-flow-api
  replicas: 1
  template:
    metadata:
      labels:
        app: artifact-flow-api
        department: artifact-flow-api
    spec:
      containers:
      - env:
        - name: DB_CONNECTION_STRING
          value: mongodb://localhost:27017
        name: artifact-flow-api
        image: us-west1-docker.pkg.dev/artifact-flow/artifact-flow-api/artifact-flow-core:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "64Mi"
            cpu: "1250m"
          limits:
            memory: "256Mi"
            cpu: "250m"


---
apiVersion: v1
kind: Service
metadata:
  name: artifact-flow-api
  namespace: artifact-flow-api
  annotations:
      external-dns.alpha.kubernetes.io/hostname: api.artifact-flow.com
  labels:
    app: artifact-flow-api
    department: artifact-flow-api
spec:
  type: LoadBalancer
  selector:
    app: artifact-flow-api
    department: artifact-flow-api
  ports:
  - name:
    port: 80
    targetPort: 8000
