version: "3"
services:
  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"

  artifact-flow-api:
    image: artifact-flow-api:latest
    ports:
      - "80:80"
    links:
      - mongodb
    environment:
      DB_CONNECTION_STRING: mongodb://mongodb:27017
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_REDIRECT_URL: ${OAUTH_REDIRECT_URL}
      OAUTH_JWT_KEY: ${OAUTH_JWT_KEY}
      OAUTH_SESSION_SECRET: ${OAUTH_SESSION_SECRET}
