name: deploy-to-gke

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Create or Delete'
        required: true
        default: 'null'
        type: choice
        options:
        - delete
        - create

jobs:
  k8s-create-or-delete:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GCP CLI
        run: curl https://sdk.cloud.google.com | bash

      - name: Docker Build + Push
        if: ${{ inputs.action }} == "create"
        run: |
          echo "$GOOGLE_CREDENTIALS" > ./google_sa_key.json
          gcloud auth activate-service-account --key-file=./google_sa_key.json
          docker build --platform linux/amd64 -f ./hosting/Dockerfile -t us-west1-docker.pkg.dev/artifact-flow/artifact-flow-api/artifact-flow-core:latest .
          gcloud auth configure-docker us-west1-docker.pkg.dev
          docker push us-west1-docker.pkg.dev/artifact-flow/artifact-flow-api/artifact-flow-core:latest
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Kubernetes Install
        run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl

      - name: Setup Gcloud Repositories
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates gnupg curl
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudotee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Kubernetes Deploy
        run: |
          gcloud container clusters get-credentials artifact-flow --region us-west1 --project artifact-flow
          kubectl ${{ inputs.action }} -f ./hosting/kubernetes/deployment.yml
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True